name: retrack
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip:
      - accelerate
      - datasets
      - diffusers
      - hydra-core
      - joblib
      - numpy
      - omegaconf
      - packaging
      - pillow
      - scipy
      - scikit-learn
      - torchmetrics
      - tqdm
      - transformers
